// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCiTEDChhGiSKueT1HhQlL-t1rvTwYiqY',
    appId: '1:423414584767:web:242e4a6611d6caf3907d0a',
    messagingSenderId: '423414584767',
    projectId: 'flutter1db-13da1',
    authDomain: 'flutter1db-13da1.firebaseapp.com',
    storageBucket: 'flutter1db-13da1.appspot.com',
    measurementId: 'G-MTLHES2WFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe1hPg-oOOTTyxqpZNjAh_GuE8gY4Tj0s',
    appId: '1:423414584767:android:224ddf1187736af1907d0a',
    messagingSenderId: '423414584767',
    projectId: 'flutter1db-13da1',
    storageBucket: 'flutter1db-13da1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUHlNtZjPktKtdGZo7v-dEyd9eCmmUNLE',
    appId: '1:423414584767:ios:1643b9d22a6942be907d0a',
    messagingSenderId: '423414584767',
    projectId: 'flutter1db-13da1',
    storageBucket: 'flutter1db-13da1.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUHlNtZjPktKtdGZo7v-dEyd9eCmmUNLE',
    appId: '1:423414584767:ios:dbe9af2b21445d57907d0a',
    messagingSenderId: '423414584767',
    projectId: 'flutter1db-13da1',
    storageBucket: 'flutter1db-13da1.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseSample.RunnerTests',
  );
}
